/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <common.h>
/* Header for class com_hht_patch_HPatchHelper */

#ifndef _Included_com_hht_patch_HPatchHelper
#define _Included_com_hht_patch_HPatchHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hht_patch_HPatchHelper
 * Method:    generatePatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hht_patch_HPatchHelper_generatePatch
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_hht_patch_HPatchHelper
 * Method:    applyPatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hht_patch_HPatchHelper_applyPatch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
